# Dockerfile.airflow
FROM apache/airflow:2.10.0

USER root

# Install Java 17 and procps
RUN apt-get update && apt-get install -y openjdk-17-jdk procps && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

USER airflow