FROM flink:1.19

ADD https://repo1.maven.org/maven2/org/apache/flink/flink-connector-kafka/3.3.0-1.19/flink-connector-kafka-3.3.0-1.19.jar /opt/flink/lib/
ADD https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.7.0/kafka-clients-3.7.0.jar /opt/flink/lib/


ADD https://repo1.maven.org/maven2/org/apache/flink/flink-connector-cassandra_2.12/3.2.0-1.19/flink-connector-cassandra_2.12-3.2.0-1.19.jar /opt/flink/lib/
ADD https://repo1.maven.org/maven2/com/datastax/cassandra/cassandra-driver-core/3.11.2/cassandra-driver-core-3.11.2.jar /opt/flink/lib/
ADD https://repo1.maven.org/maven2/com/datastax/cassandra/cassandra-driver-mapping/3.11.2/cassandra-driver-mapping-3.11.2.jar /opt/flink/lib/
ADD https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.jar /opt/flink/lib/
ADD https://repo1.maven.org/maven2/com/google/guava/guava/25.1-jre/guava-25.1-jre.jar /opt/flink/lib/